export const SAVE_POSITION = 'SAVE_POSITION';
export const SAVE_WEATHER = 'SAVE_WEATHER';
export const SAVE_ERROR_DESC = 'SAVE_ERROR_DESC';
export const SAVE_CURRENT_POSITION_KEY = 'SAVE_CURRENT_POSITION_KEY';
